framework: jest
preRun:
     command:
        - pnpm install -f ./packages/hoppscotch-app/package.json
preMerge:
  pattern:
    - "./packages/hoppscotch-app/helpers/__tests__/*.spec.js"
postMerge:
  pattern:
    - "./packages/hoppscotch-app/helpers/__tests__/*.spec.js"
postRun:
     command:
        - pnpm --version
configFile: "packages/hoppscotch-app/jest.config.js"
version: 1.0
