framework: jest
preRun:
     command:
        - pnpm install -w -f  ./packages/hoppscotch-app
preMerge:
  pattern:
    - "./packages/hoppscotch-app/helpers/__tests__/*.spec.js"
postMerge:
  pattern:
    - "./packages/hoppscotch-app/helpers/__tests__/*.spec.js"
postRun:
     command:
        - pnpm --version
configFile: "packages/hoppscotch-app/jest.config.js"
version: 1.0
